# Generated by Django 5.1.1 on 2024-09-15 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user_role',
        ),
    ]
