# Generated by Django 5.1.1 on 2024-09-16 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0002_remove_student_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='user_role',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='user_role',
        ),
        migrations.RemoveField(
            model_name='clinicstaff',
            name='user_role',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
