# Generated by Django 4.2.15 on 2024-09-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=50)),
            ],
        ),
    ]
