# Generated by Django 4.2.15 on 2024-09-21 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0003_timetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='course_name',
        ),
        migrations.AddField(
            model_name='timetable',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ims.course'),
            preserve_default=False,
        ),
    ]
