# Generated by Django 4.2.15 on 2024-09-23 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0005_lecturer_approved_student_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400'), ('500', '500')], max_length=255)),
                ('adviser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ims.lecturer')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.department')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='ims.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.department'),
        ),
    ]
