# Generated by Django 4.2.15 on 2024-09-23 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0006_department_level_student_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='year_of_study',
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ims.level'),
            preserve_default=False,
        ),
    ]
