# Generated by Django 4.2.15 on 2024-09-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0007_remove_student_year_of_study_student_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='carry_over',
            field=models.ManyToManyField(to='ims.course'),
        ),
    ]
