# Generated by Django 4.2.15 on 2024-09-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0008_student_carry_over'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='carry_over',
            field=models.ManyToManyField(null=True, to='ims.course'),
        ),
    ]
