# Generated by Django 4.2.15 on 2024-09-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0009_alter_student_carry_over'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Gaurdian_contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='matric',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='reg_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='carry_over',
            field=models.ManyToManyField(blank=True, null=True, to='ims.course'),
        ),
    ]
